use wazir_drop::{movegen, Piece, Square};

#[test]
fn test_move_bitboard() {
    assert_eq!(
        movegen::move_bitboard(Piece::Alfil, Square::D4).to_string(),
        "\
........
.x...x..
........
........
........
.x...x..
........
........
"
    );

    assert_eq!(
        movegen::move_bitboard(Piece::Dabbaba, Square::D4).to_string(),
        "\
........
...x....
........
.x...x..
........
...x....
........
........
"
    );

    assert_eq!(
        movegen::move_bitboard(Piece::Ferz, Square::D4).to_string(),
        "\
........
........
..x.x...
........
..x.x...
........
........
........
"
    );

    assert_eq!(
        movegen::move_bitboard(Piece::Knight, Square::D4).to_string(),
        "\
........
..x.x...
.x...x..
........
.x...x..
..x.x...
........
........
"
    );

    assert_eq!(
        movegen::move_bitboard(Piece::Wazir, Square::D4).to_string(),
        "\
........
........
...x....
..x.x...
...x....
........
........
........
"
    );

    // From a corner.
    assert_eq!(
        movegen::move_bitboard(Piece::Knight, Square::H8).to_string(),
        "\
........
........
........
........
........
......x.
.....x..
........
"
    );
}

#[test]
fn test_validate_from_to() {
    assert!(movegen::validate_from_to(Piece::Alfil, Square::D4, Square::F6).is_ok());
    assert!(movegen::validate_from_to(Piece::Alfil, Square::D4, Square::D5).is_err());
    assert!(movegen::validate_from_to(Piece::Knight, Square::A4, Square::B2).is_ok());
    assert!(movegen::validate_from_to(Piece::Knight, Square::A4, Square::C6).is_err());
}
